name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.20']
    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Go ${{matrix.go}}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Show Go Version and environment
        run: |
          go version
          go env
      - name: Install dependencies
        run: |
          make
          GOBIN=$HOME/.local/bin go install honnef.co/go/tools/cmd/staticcheck@2023.1.3
      - name: Run tests
        run: |
          make fmt
          make test
          make vet
          make staticcheck

  e2e:
    name: end-to-end test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make all
        uses: docker://golang:latest
        with:
          entrypoint: bash
          args: -c "make all GOFLAGS=-buildvcs=false"
      - uses: actions/setup-go@v3
      - uses: docker/setup-buildx-action@v2
      - name: e2e
        run: |
          GOBIN=$HOME/.local/bin go install github.com/ricardobranco777/simplepki
          bash -x tests/e2e.sh
